#服务消费者
server:
  port: 8020
spring:
  application:
    #服务消费者名称
    name: consumer
eureka:
  client:
    #注册中心地址
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    #注册ip到注册中心
    prefer-ip-address: true