#服务提供者
server:
  port: 8010
spring:
  application:
    #服务提供者名称
    name: provider
eureka:
  client:
    #注册中心地址
    service-url:
      defaultZone: http://localhost:8761/eureka/
      #是否将当前服务的ip注册到注册中心里面
  instance:
    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 10
#    lease-expiration-duration-in-seconds: 30
